### ISSUE TITLE
SVN authentication using --username and --password

### ISSUE THREAD

**Issue by dalu93** [CocoaPods/cocoapods-downloader#48]
Hi,
As I said there: https://github.com/CocoaPods/CocoaPods/issues/4086#issuecomment-135067121 I have to export repo with those two parameters because my server refuse http basic authentication and it doesn't support `svn+ssh` protocol.
Unfortunately Cocoapods is launching on OS X Server and I can not store the credentials in Keychain with the server user. I tried to copy the keychain-item in the server user keychain, but it is still not working. My only solution is to populate `--username` and `--password` parameters. How can I do this? Thanks

**Comment by segiddins** [comment]
Might http://stackoverflow.com/a/8330523/1675979 work for you in the meantime?

**Comment by dalu93** [comment]
Tried setting `servers` file as

    [groups]
    namegroup=repohost
    [namegroup]

**Comment by segiddins** [comment]
¯\_(ツ)_/¯

**Comment by huangzhijia** [comment]
have any solutions ? @dalu93
