### ISSUE TITLE
Don't force usage of a ~/.netrc file when remote server requires authentication

### ISSUE THREAD

**Issue by sguillope** [CocoaPods/cocoapods-downloader#55]
#54 added the option `--netrc` to the `curl` call in the `HTTP` module.

However when downloading using the `HTTP` module, `curl` should use `--netrc-optional` instead of the more restrictive `--netrc` option. This allows users to choose to specify the authentication credentials through the url instead of having to set them up in a `~/.netrc` file

See CocoaPods/CocoaPods#5318

**Comment by mackoj** [comment]
I have the same issue.
Please consider tag a new version of cocoapods with it.

Thanks,
