### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by danielribeiro** [CocoaPods/cocoapods-downloader#60]
Hi,

Is there any plan to add a proxy support? This way artifacts can be served from internal http proxies transparently.

Alternatively: if I make a PR adding such support, what are your thoughts on adding such functionality?

Cheers,
- Daniel

**Comment by segiddins** [comment]
All HTTP downloading is done via curl (https://github.com/CocoaPods/cocoapods-downloader/blob/master/lib/cocoapods-downloader/http.rb#L93) so it'll use whatever curl does to proxy
