### ISSUE TITLE
Are remote shares supported?

### ISSUE THREAD

**Issue by szalap** [CocoaPods/cocoapods-downloader#67]
Is there a way to access remote shares through cocoapods? I know it works when I mount share through samba to Volumes - it's treated as normal :path that time. But I still want to be able to have it done from end-2-end using cocoapods.

**Comment by orta** [comment]
So long as it can be accessed via a `cd` or `cp` through the terminal, I'd expect the downloader to be able to work with when using `:path`. You could also try a similar approach with local git repos too, they can work across the filesystem.

**Comment by szalap** [comment]
Thanks Orta, and that's right, though it's still has to be mounted first. I guess another shot at this is to add mounting logic into pre-install hook, so the share is ready when cocoapods tries to read it through :path during "pod install".

**Comment by orta** [comment]
Yeah, you could probably make a CocoaPods plugin that handles the mounting aspect for you too, or just put it in at the top of your Podfile, it is just a Ruby file.
